* 流程
** 1、成立清算组
　　法院应当自宣告债务企业破产之日起15日内成立清算组，接管破产企业。清算组由法院从公司的主管部门、政府有关部门和专业人员中指定，也可以聘请中国注册会计师和律师参加。清算组负责破产财产的保管、清理、估价、处理和分配。清算组应对人民法院负责并报告工作，接受法院的监督。我国《公司法》规定，清算组在清算期间行使下列职权：
　　（1）清理公司财产，分别编制资产负债表和财产清单；
　　（2）通知或者公告债权人；
　　（3）处理与清算有关的公司未了结的业务；
　　（4）清缴所欠税款；
　　（5）清理债权、债务；
　　（6）处理公司清偿债务后的剩余财产；
　　（7）代表公司参与民事诉讼活动。
** 2、通知债权人申报债权
　　清算组应当自成立之日起10日内通知债权人，并于60日内在报纸上至少公告三次，公告和通知中应当规定第一次债权人会议召开的日期。
** 3、召开债权人会议。
　　所有债权人均为债权人会议成员。第一次债权人会议由人民法院召集，应当在债权申请期限届满后15日内召开。以后的债权人会议在人民法院或者会议主席认为必要时召开，也可以在清算组或占无财产担保债权总额的1/4以上的债权人要求时召开。
** 4、确认破产财产。
　　破产财产指用以清偿债务的全部财产，主要包括：
　　（1）宣告破产时破产企业经营管理的全部财产；
　　（2）破产企业在破产宣告后至破产程式终结前所取得的财产；
　　（3）应当由破产企业行使的其他财产权利。已作为担保物所担保的债务数额的，超过部分属于破产财产。破产企业内属于他人的财产，应由该财产的权利人通过清算组取回。
** 5、确认破产债权。
　　破产债权指宣告破产前就已成立的、对破产人发生的、依法申报确认并从破产财产中获得公开清偿的可强制性执行的财产清求权。主要包括：
　　（1）宣告破产前成立的无财产担保的债权和放弃优先受偿权利的有财产担保的债权；
　　（2）宣告破产时未到期的债权，视为已到期债权，但是应当减去至期日的利息；
　　（3）宣告破产前成立的有关财产担保的债权，债权人享有就该担保物优先受偿的权利。如果该项债权数额超过担保物的价款的，未受清偿的部分作为破产债权。债权人参加破产程式的费用不得作为破产债权。
** 6、拨付破产费用。
　　破产费用指在破产程式中为破产债权人的共同利益而由破产财产中支付的费用，主要包括：
　　（1）破产财产的管理、变卖和分配所需要的费用，包括聘任工作人员的费用；
　　（2）破产案件的诉讼费用；
　　（3）为债权人的共同利益而在破产程式中支付的其他费用。破产费用应当从破产财产中优先拨付。
** 7、破产财产清偿顺序。
　　破产财产在优先拨付破产费用后，按照下列顺序清偿：
　　（1）破产企业所欠职工工资和劳动保险费用；
　　（2）破产企业所欠税款；
　　（3）破产债权。破产财产不足清偿同一顺序的清偿要求的，按照比例分配。
　　有些国家（如美国），在法律中规定了详细的债权清偿等级，受有效抵押权所担保的债权，将在作为其担保物的财产变卖所得价款范围内首先获得清偿。如果所得价款不足以清偿有财产担保债权人的债权，不足金额作为无担保非优先债权，或一般无担保债权。无担保债权分为优先和非优先二级。无担保优先债权应在支付无担保非优先债权之前全数清偿。无担保优先债权共分六级，第一级债权（管理费用）应在支付第二级债权之前全数偿还，还并依此类推。然而，在这六级中，任何一级可用的现金不足以支付该级的所有债权，则按比例清偿。无担保非优先债权也应按相同的现金分配程式清偿。只有在所有债权人的债权均受清偿之后才能分配给股东（所有者）。
** 8、破产清算的结束。
　　经过上述破产清算程式后，清算组应当编制破产清算结束报告，并出具清算期内的各种报表连同各种财务账册，经中国注册会计师验证后，报授权部门审批。
** 9、登报声明
　　经批准后再向工商行政管理部门和税务部门注销登记并在省级或者市级以上报纸上刊登公告。